name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0,30 * * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1.2 Safari/605.1.15' https://api.booba.tv/ | jq . > api-data.json
    - name: Commit and push if it changed
      run: |-
        git config user.name "a9"
        git config user.email "its+github@a9.wtf"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
